/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateForm: typeof import('./src/components/player-actions/CreateForm.vue')['default']
    EditForm: typeof import('./src/components/player-actions/EditForm.vue')['default']
    GameInfo: typeof import('./src/components/game-info/GameInfo.vue')['default']
    GameSettings: typeof import('./src/components/game-settings/GameSettings.vue')['default']
    PlayerCard: typeof import('./src/components/player-card/PlayerCard.vue')['default']
    SettingsField: typeof import('./src/components/game-settings/SettingsField.vue')['default']
  }
}
