/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    CreateForm: typeof import('./src/components/player-actions/CreateForm.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    EditForm: typeof import('./src/components/player-actions/EditForm.vue')['default']
    GameInfo: typeof import('./src/components/game-info/GameInfo.vue')['default']
    GameSettings: typeof import('./src/components/game-settings/GameSettings.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PlayerCard: typeof import('./src/components/player-card/PlayerCard.vue')['default']
    SettingsField: typeof import('./src/components/game-settings/SettingsField.vue')['default']
  }
}
